### ISSUE TITLE
ContractFunctionExecutionError: HTTP request failed.

### ISSUE THREAD

**Issue by VictorECDSA** [HelheimLabs/autochessia#199]
Version:
develop
439c3d6e

After execute the command below:
```
pnpm dev
```

I go to http://localhost:3000/ in explorer, and click the button 'Single Play', and then wait a while. I hit an error on the 'singlePlay()' of Actions, as below:
```
ContractFunctionExecutionError: HTTP request failed.

URL: https://flashlayer.alt.technology/autochessia37806fd60
Request body: {"method":"eth_call","params":[{"from":"0x52e5145EaF688dD5b36E371E28F419c8E4112903","data":"0xe4b4792c","to":"0xa39f9c7590c220aeDFA98038D31fa51B5fed5a18"},"pending"]}
 
Raw Call Arguments:
  from:  0x52e5145EaF688dD5b36E371E28F419c8E4112903
  to:    0xa39f9c7590c220aeDFA98038D31fa51B5fed5a18
  data:  0xe4b4792c
 
Contract Call:
  address:   0xa39f9c7590c220aeDFA98038D31fa51B5fed5a18
  function:  singlePlay()
  sender:    0x52e5145EaF688dD5b36E371E28F419c8E4112903

Docs: https://viem.sh/docs/contract/simulateContract.html
Details: Failed to fetch
Version: viem@1.13.2
    at getContractError (http://localhost:3000/node_modules/.vite/deps/chunk-FOH7TKH3.js?v=83bcda20:988:10)
    at simulateContract (http://localhost:3000/node_modules/.vite/deps/chunk-FOH7TKH3.js?v=83bcda20:1678:11)
    at async a (http://localhost:3000/node_modules/.vite/deps/chunk-WLWLZ3I7.js?v=83bcda20:20782:151)
    at async H (http://localhost:3000/node_modules/.vite/deps/chunk-WLWLZ3I7.js?v=83bcda20:20784:11)
```

**Comment by noyyyy** [comment]
For local preview, you need to switch to foundy testnet. 
![image](https://github.com/HelheimLabs/autochessia/assets/59097122/58f84370-eaf9-4543-a9cb-f499ddc73261)

**Comment by VictorECDSA** [comment]
> For local preview, you need to switch to foundy testnet. ![image](https://private-user-images.githubusercontent.com/59097122/289487336-58f84370-eaf9-4543-a9cb-f499ddc73261.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyOTc3NTIsIm5iZiI6MTcwMjI5NzQ1MiwicGF0aCI6Ii81OTA5NzEyMi8yODk0ODczMzYtNThmODQzNzAtZWFmOS00NTQzLWE5Y2ItZjQ5OWRkYzczMjYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDEyMjQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjYTU2ZDdjNjU4ZTEzMGFmNWQ3YWZjNTFmYmNhNjc5MDFjZTI1NTM1ZjYyMzVhNWM0MjlkMjBiNWNkMjFlYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FgR3r05asXToRXxpyLLl3BmsVSNErnoQ9prRhe7sucs)

Thank you! I can enter Single Play now. But the status bar on the right blocking my game interface. Could you tell me how to "collapse" it?

<img width="1446" alt="WeChatWorkScreenshot_5970e599-a468-42c7-b840-8c02611bb6a6" src="https://github.com/HelheimLabs/autochessia/assets/26361852/3a6cb950-8828-4dd8-8c79-67de1bfc0e83">

**Comment by noyyyy** [comment]
press `tab`

**Comment by VictorECDSA** [comment]
> press `tab`

Oh thank you, I see it.

But I still have some questions.

Firstly, according to 'How to Play', there should be a 'Refresh Heros' button, but I haven't see it, so I have not heros. So I can not perform any operation. I can just wait for the time pass by.

Secondly, there are some errors on the 'Actions', present periodically. I know it is the operation of bot. But some 'tick' are failure. And the error info is as below. Is this normal?
```
ContractFunctionExecutionError: The contract function "tick" reverted with the following reason:
preparing time

Contract Call:
  address:   0xe3a6d6d5570f1d87d45036eac17342ffe32d8f46
  function:  tick(uint32 _gameId, address _player)
  args:          (3, 0x52e5145EaF688dD5b36E371E28F419c8E4112903)
  sender:    0x52e5145EaF688dD5b36E371E28F419c8E4112903

Docs: https://viem.sh/docs/contract/simulateContract.html
Version: viem@1.13.2
    at getContractError (http://localhost:3000/node_modules/.vite/deps/chunk-FOH7TKH3.js?v=83bcda20:988:10)
    at simulateContract (http://localhost:3000/node_modules/.vite/deps/chunk-FOH7TKH3.js?v=83bcda20:1678:11)
    at async a (http://localhost:3000/node_modules/.vite/deps/chunk-WLWLZ3I7.js?v=83bcda20:20782:151)
    at async H (http://localhost:3000/node_modules/.vite/deps/chunk-WLWLZ3I7.js?v=83bcda20:20784:11)
```

<img width="1714" alt="WeChatWorkScreenshot_ff6aa280-1f51-4bd6-9881-325e9249ecc4" src="https://github.com/HelheimLabs/autochessia/assets/26361852/9bda0223-cf87-4199-8c70-f259cb081f73">

**Comment by fenghaoming** [comment]
> > press `tab`
> 
> Oh thank you, I see it.
> 
> But I still have some questions.
> 
> Firstly, according to 'How to Play', there should be a 'Refresh Heros' button, but I haven't see it, so I have not heros. So I can not perform any operation. I can just wait for the time pass by.
> 
> Secondly, there are some errors on the 'Actions', present periodically. I know it is the operation of bot. But some 'tick' are failure. And the error info is as below. Is this normal?
> 
> ```
> ContractFunctionExecutionError: The contract function "tick" reverted with the following reason:
> preparing time
> 
> Contract Call:
>   address:   0xe3a6d6d5570f1d87d45036eac17342ffe32d8f46
>   function:  tick(uint32 _gameId, address _player)
>   args:          (3, 0x52e5145EaF688dD5b36E371E28F419c8E4112903)
>   sender:    0x52e5145EaF688dD5b36E371E28F419c8E4112903
> 
> Docs: https://viem.sh/docs/contract/simulateContract.html
> Version: viem@1.13.2
>     at getContractError (http://localhost:3000/node_modules/.vite/deps/chunk-FOH7TKH3.js?v=83bcda20:988:10)
>     at simulateContract (http://localhost:3000/node_modules/.vite/deps/chunk-FOH7TKH3.js?v=83bcda20:1678:11)
>     at async a (http://localhost:3000/node_modules/.vite/deps/chunk-WLWLZ3I7.js?v=83bcda20:20782:151)
>     at async H (http://localhost:3000/node_modules/.vite/deps/chunk-WLWLZ3I7.js?v=83bcda20:20784:11)
> ```
> 
> <img alt="WeChatWorkScreenshot_ff6aa280-1f51-4bd6-9881-325e9249ecc4" width="1714" src="https://private-user-images.githubusercontent.com/26361852/289545271-9bda0223-cf87-4199-8c70-f259cb081f73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMDA0MDYsIm5iZiI6MTcwMjMwMDEwNiwicGF0aCI6Ii8yNjM2MTg1Mi8yODk1NDUyNzEtOWJkYTAyMjMtY2Y4Ny00MTk5LThjNzAtZjI1OWNiMDgxZjczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDEzMDgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzZmRlNGY2NzVjODU3MmM5MjQ4ZGJmMTBlY2EyZTI2MzRmZTY1OWZmYzU5N2NlN2YxYTJmYjI2NWQ3ZjNkMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xKDB3BMaR2wrrOCucdZzJlTGeIdKCjDySO3WtGIh4i4">

**Comment by noyyyy** [comment]
@fenghaoming Thanks for your trying. 

The shop btn is a little covert so that you need to click the `autochessia` to open it. We are making a new interface in #191

Secondly, the error of tick is expected.

It's not ready for playtest now but you can read code to learn how it work.

**Comment by VictorECDSA** [comment]
> @fenghaoming Thanks for your trying.
> 
> The shop btn is a little covert so that you need to click the `autochessia` to open it. We are making a new interface in #191
> 
> Secondly, the error of tick is expected.
> 
> It's not ready for playtest now but you can read code to learn how it work.

Thanks. I am reading the source code of such a charming game.
