### ISSUE TITLE
support multiplayer(8 in maximum) game

### ISSUE THREAD

**Issue by ClaudeZsb** [HelheimLabs/autochessia#34]

**Comment by ClaudeZsb** [comment]
WIP. #36

**Comment by ClaudeZsb** [comment]
Contract side is almost done. There are some changes in tables and matching process. Please update client side accordingly. @aLIEzsss4 

Any questions and problems related to this feature can be posted here.

**Comment by aLIEzsss4** [comment]
done!
https://github.com/HelheimLabs/autochessia/pull/50
