### ISSUE TITLE
private room

### ISSUE THREAD

**Issue by ClaudeZsb** [HelheimLabs/autochessia#35]
Two propositions

1. private room is combined with a hash of password; a player need to prove in front-end that he knows the password and then joins in the room with the proof; contract should be able to verify the proof.
2. player with a valid signature of room creator can join in a private room.

We're going to implement this feature through the first way, which will enrich our experience of zk development.

**Comment by ClaudeZsb** [comment]
Circuit is done. I also wrote an example of proving and verifying in js and put it into `packages/client/src/snarkjsHelper` folder. 

I did also wrtite some code in `typescript` which uses directly the `snarkjs` module. Not tested. My main purpose is to demonstrate how could we generate a proof in client for the fact that someone knows the password of a specific waiting room. To make it really worked, I do need your help @aLIEzsss4 @noyyyy

**Comment by noyyyy** [comment]
> I did also wrtite some code in `typescript` which uses directly the `snarkjs` module. Not tested. My main purpose is to demonstrate how could we generate a proof in client for the fact that someone knows the password of a specific waiting room. To make it really worked, I do need your help @aLIEzsss4 @noyyyy

Great job. We will do the rest.

**Comment by aLIEzsss4** [comment]
done!
https://github.com/HelheimLabs/autochessia/pull/50
